package org.hmxlabs.techtest.server.persistence.repository;

import java.util.List;
import java.util.Optional;

import org.hmxlabs.techtest.server.persistence.BlockTypeEnum;
import org.hmxlabs.techtest.server.persistence.model.DataBodyEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface DataStoreRepository extends JpaRepository<DataBodyEntity, Long> {
    /**
     * This method is generated by Spring at compile time.
     * The method name tells Spring to match the BlockType within the DataHeaderEntity referenced by the DataBlockEntity.
     * @param type - the type every retrieved type should have.
     * @return a list of all DataBlockEntities with the provided type.
     */
    List<DataBodyEntity> findByDataHeaderEntity_Blocktype(BlockTypeEnum type);
    Optional<DataBodyEntity> findByDataHeaderEntity_Name(String blockName);
}
