package org.hmxlabs.techtest.server.persistence.repository;

import java.util.Optional;

import org.hmxlabs.techtest.server.persistence.model.DataHeaderEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Handles all direct interaction with the database's DataHeader table
 */
@Repository
public interface DataHeaderRepository extends JpaRepository<DataHeaderEntity, Long> {

    /**
     * This method is generated by Spring at compile time.
     * The method name tells Spring to match the name within the DataHeaderEntity referenced by the name.
     * Since the name is unique, it will only return 1 or 0 entries, hence an Optional<> return type.
     * 
     * @param name - the name of the data to retrieve.
     * @return a Optional<> containing the DataHeaderEntity with the provided name.
     */
    Optional<DataHeaderEntity> findByName(String blockName);
}
